# Run the parser module
parse:
	cd ../.. && PYTHONPATH=/Users/jbalkovec/Desktop/Knapsack/Tests/Python python -m Tests.Python.my_parser

# Run the analysis module
analyze:
	cd ../.. && PYTHONPATH=/Users/jbalkovec/Desktop/Knapsack/Tests/Python python -m Tests.Python.analysis
